name: CI

on:
  # Workflow sẽ được kích hoạt khi push code mới vào nhánh main
  push:
    branches: [ main ]
  # Workflow sẽ được kích hoạt khi tạo pull request vào nhánh main
  pull_request:
    branches: [ main ]
    
jobs:
  firebase-deploy:
    # Workflow được chạy trên môi trường ubuntu phiên bảng mới nhất
    runs-on: ubuntu-latest

    steps:
      # Sử dụng code trên nhánh master của Github repository: github.com/actions/checkout để chạy workflow
      - uses: actions/checkout@main
      # Sử dụng code trên nhánh master của Github repository: github.com/actions/setup-node để cài đặt NodeJS
      - uses: actions/setup-node@main
        with:
          node-version: '10.x'
      # Chạy lệnh npm install để cài đặt các thư viện cần thiệt cho ứng dụng
      - name: Install Dependencies
        run: npm install
      # Chạy lệnh npm install build để cài đặt ứng dụng trước khi deploy
      - name: Build
        run: npm run build
      # Sử dụng code trên nhánh master của Github repository: github.com/w9jds/firebase-action 
      # để chạy deploy ứng dụng lên Firebase Hosting
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        # Khai báo Firebase token của ứng dụng
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
